name: ItemDrop
description: ItemDrop
author: Color_yr
main: Color_yr.ItemDrop.ItemDrop
version: 1.0.0
api-version: 1.13
commands:
    item:
        usage: /item help
        permission: ItemDrop.admin
